version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rawly_api
    restart: always
    network_mode: "host"
    env_file:
      - .env
    volumes:
      # Mount host uploads folder to persist user avatars, posts, and videos
      - ./uploads:/app/uploads
